{
	"openapi": "3.0.0",
	"info" : {
		"title": "Pixit Documentation",
		"description": "This is an API Test",
		"version": "1.0.0",
		"contact": {
			"email": "victornfb@outlook.com"
		}
	},
	"paths": {
		"/sessions": {
			"post": {
				"tags": ["Session"],
				"summary": "Create a new session",
				"description": "Create a new session for a existing user",
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"email": {
										"type": "string"
									},
									"password": {
										"type": "string"
									}
								},
								"example": {
									"email": "admin@pixit.com.br",
									"password": "admin"
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Session created",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"user": {
											"type": "object",
											"properties": {
												"id": {
													"type": "number"
												},
												"name": {
													"type": "string"
												},
												"email": {
													"type": "string"
												}
											}
										},
										"token": {
											"type": "string"
										}
									},
									"example": {
										"user": {
											"id": 1,
											"name": "Admin",
											"email": "admin@pixit.com.br"
										},
										"token": "example-access-token"
									}
								}
							}
						}
					},
					"400": {
						"description": "Email or password incorrect",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									},
									"example": {
										"message": "Email or password incorrect"
									}
								}
							}
						}
					}
				}
			}
		},
		"/users": {
			"get": {
				"tags": ["User"],
				"summary": "List all users",
				"description": "List all users",
				"security": [
					{
						"bearerAuth": []
					}
				],
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"type": "object",
										"properties": {
											"id": {
												"type": "string"
											},
											"name": {
												"type": "string"
											},
											"email": {
												"type": "string"
											},
											"created_at": {
												"type": "string"
											},
											"updated_at": {
												"type": "string"
											}
										},
										"example": {
											"id": 1,
											"name": "Admin",
											"email": "admin@pixit.com.br",
											"updated_at": "2022-07-16T14:57:58.000Z",
											"created_at": "2022-07-16T14:57:58.000Z"
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									},
									"example": {
										"message": "Invalid token || Invalid authorization header"
									}
								}
							}
						}
					}
				}
			},
			"post": {
				"tags": ["User"],
				"summary": "Create a new user",
				"description": "Create a new user",
				"security": [
					{
						"bearerAuth": []
					}
				],
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"password": {
										"type": "string"
									},
									"email": {
										"type": "string"
									}
								},
								"example": {
									"name": "John Doe",
									"email": "john@doe.com.br",
									"password": "@John123"
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Session created",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"id": {
											"type": "number"
										},
										"name": {
											"type": "string"
										},
										"email": {
											"type": "string"
										},
										"created_at": {
											"type": "string"
										},
										"updated_at": {
											"type": "string"
										}
									},
									"example": {
										"id": 1,
										"name": "Admin",
										"email": "admin@pixit.com.br",
										"created_at": "2022-07-16T15:38:58.000Z",
										"updated_at": "2022-07-16T15:38:59.000Z"
									}
								}
							}
						}
					},
					"400": {
						"description": "Bad request",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									},
									"example": {
										"message": "Required fields missing || User already exists"
									}
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									},
									"example": {
										"message": "Invalid token || Invalid authorization header"
									}
								}
							}
						}
					}
				}
			},
			"put": {
				"tags": ["User"],
				"summary": "Update a user",
				"description": "Update a user",
				"security": [
					{
						"bearerAuth": []
					}
				],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "User Id",
						"required": true
					}
				],
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"password": {
										"type": "string"
									}
								},
								"example": {
									"name": "John Doe",
									"password": "new-password"
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"id": {
											"type": "number"
										},
										"name": {
											"type": "string"
										},
										"email": {
											"type": "string"
										},
										"created_at": {
											"type": "string"
										},
										"updated_at": {
											"type": "string"
										}
									},
									"example": {
										"id": 1,
										"name": "Admin",
										"email": "admin@pixit.com.br",
										"created_at": "2022-07-16T15:38:58.000Z",
										"updated_at": "2022-07-16T15:40:00.000Z"
									}
								}
							}
						}
					},
					"400": {
						"description": "Bad request",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									},
									"example": {
										"message": "User not found"
									}
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									},
									"example": {
										"message": "Invalid token || Invalid authorization header"
									}
								}
							}
						}
					}
				}
			},
			"delete": {
				"tags": ["User"],
				"summary": "Update a user",
				"description": "Update a user",
				"security": [
					{
						"bearerAuth": []
					}
				],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "User Id",
						"required": true
					}
				],
				"responses": {
					"204": {
						"description": "Success"
					},
					"400": {
						"description": "Bad request",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									},
									"example": {
										"message": "User not found"
									}
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									},
									"example": {
										"message": "Invalid token || Invalid authorization header"
									}
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"securitySchemes": {
			"bearerAuth": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		}
	}
}